[[proxy]]
rewrite = "/hello"
backend = "http://localhost:3000/hello"

[[hooks]]
stage = "pre_build"
command = "tailwindcss"
command_arguments = [
    "-i",
    "assets/css/input.css",
    "-o",
    "assets/css/output.css",
]
